- .dockerignore
- Dockerfile
- docker-compose.yml
With this PR we don't have to run service every time. We just run compose and service docker image is created and loaded.
> Added docker for service and updated compose

- README.md
We need to find out how to make this command work, since postgres image does not have wget installed:
docker exec -it api_postgres_1 bash -c  "wget https://plezanje.info/storage/db_lite.sql && psql -U plezanjenet -f db_lite.sql"
> Download dump and run it in postgres container

- src/core/middleware/check-role.middleware.spec.ts
- src/core/middleware/check-role.middleware.ts
- src/users/entities/user.entity.ts
> Protect user data with fieldMiddleware

- package.json
Just a small PR with update to `package.json`. We added migration commands.
> updated package.json with migration commands

- src/crags/dtos/find-crags.input.ts
- src/crags/resolvers/crags.resolver.ts
- src/crags/services/crags.service.ts
> Hide empty crags

- src/crags/decorators/min-crag-status.decorator.ts
- src/crags/dtos/find-crags.input.ts
- src/crags/resolvers/countries.resolver.ts
- src/crags/resolvers/crags.resolver.ts
- src/crags/services/crags.service.ts
> MinCragStatus decorator

- src/crags/entities/difficulty-vote.entity.ts
- src/migration/1640539327798-addDifficultyCalculation.ts
closes #42
Add trigger to db that recalculates route difficulty on every difficulty vote add/change/delete.
> Recalculate route difficulty in db function, when votes are cast.

- src/crags/entities/route.entity.ts
- src/crags/resolvers/crags.resolver.ts
- src/crags/resolvers/routes.resolver.ts
- src/crags/services/routes.service.ts
- src/migration/1640288411208-route-slug.ts
> Route slugs

- src/crags/dtos/find-areas.input.ts
- src/crags/entities/area.entity.ts
- src/crags/resolvers/areas.resolver.ts
- src/crags/resolvers/countries.resolver.ts
- src/crags/services/areas.service.ts
- src/migration/1640603902543-areas-rework.ts
- src/migration/1640898554714-areas-slug.ts
add area type, descirption and hierarchy to area
migration to update from legacy field
> Upgrade areas with additional data

- src/migration/1640539327798-addDifficultyCalculation.ts
- src/migration/1641235194341-recountCragRoutes.ts
- src/migration/1641238046424-minMaxRouteDifficultyOnCrag.ts
Test this by:
- adding a route to change route count,
- changing the route's difficulty to change min/max difficulty,
- adding some difficulty votes to indirectly change min/max difficulty...
> Add db triggers to db for route count, min difficulty, max difficulty of a crag.

- src/activities/dtos/create-activity-route.input.ts
- src/activities/entities/activity-route.entity.ts
- src/activities/services/activity-routes.service.ts
routeId is mandatory now when adding activity routes. 
Also fixes ignoring position field on displaying activity routes log.
Test by logging some routes. then displaying the log, which should have routes sorted in same order that the user has entered them.
> Remove custom route in activity

- src/auth/exceptions/token-expired.exception.ts
- src/auth/guards/roles.guard.ts
- src/auth/guards/user-auth.guard.ts
- src/auth/services/auth.service.ts
- src/auth/strategies/jwt.strategy.ts
- src/core/interfaces/request-user.interface.ts
- src/core/interfaces/request.interface.ts
- src/migration/1641934161262-user-last-password-change.ts
- src/users/entities/user.entity.ts
- src/users/interfaces/login-response.class.ts
- src/users/interfaces/token-response.class.ts
- src/users/resolvers/users.resolver.ts
- src/users/services/users.service.ts
I suggest testing with the corresponding frontend PR:
https://github.com/plezanje-net/web/pull/147
> Respond with user object on login, validate user in jwt validation

- src/activities/services/activity-routes.service.ts
- src/migration/1642188200690-club-member-status.ts
- src/notification/services/notification.service.ts
- src/notification/templates/club-membership-confirmation.html.hbs
- src/notification/templates/club-membership-confirmation.plain.hbs
- src/users/entities/club-member.entity.ts
- src/users/resolvers/club-members.resolver.ts
- src/users/services/club-members.service.ts
- src/users/services/clubs.service.ts
**!! watch out when testing this because real emails will be sent to added club members !!**
Test this along with the web PR with same name.
> Club member status

- src/crags/dtos/find-countries.input.ts
- src/crags/resolvers/countries.resolver.ts
- src/crags/services/countries.service.ts
- src/crags/services/ice-falls.service.ts
Added icefall resolver to country and some count fields
Test with https://github.com/plezanje-net/web/pull/173
> Icefall reorganize

- src/notification/services/notification.service.ts
- src/notification/templates/account-confirmation.html.hbs
- src/notification/templates/account-confirmation.plain.hbs
- src/notification/templates/password-recovery.html.hbs
- src/notification/templates/password-recovery.plain.hbs
- src/users/resolvers/users.resolver.ts
Minor fixes.
See commit messages for info. 
Testing this should be straightforward.
> Fix various minor bugs

- src/activities/entities/activity-route.entity.ts
- src/activities/entities/activity.entity.ts
- src/activities/resolvers/activities.resolver.ts
- src/activities/resolvers/activity-routes.resolver.ts
- src/activities/services/activities.service.ts
- src/activities/services/activity-routes.service.ts
- src/crags/entities/difficulty-vote.entity.ts
- src/crags/entities/route.entity.ts
- src/migration/1645447461580-activity-route-cascade.ts
- src/migration/1646397701416-fixRedpointAscentTypes.ts
- src/migration/1646843392363-convertRepeatOnDeleteActivityRouteTrigger.ts
- src/migration/1647008469526-deleteDiffAndBeautyVoteOnDeleteARTrigger.ts
Added delete mutations for activities & activity logs, the mutation is for cascading activity routes.
Test with https://github.com/plezanje-net/web/pull/162
> Activity & activity route mutations

- src/crags/dtos/find-crags.input.ts
- src/crags/services/crags.service.ts
Adding crag type param to crag list dto. Test with https://github.com/plezanje-net/web/pull/259 to see the difference - if you select multipitch or all route types on crag list, alpine crags won't be there anymore.
> Crag type param

- src/crags/entities/route-event.entity.ts
- src/crags/entities/route.entity.ts
test with https://github.com/plezanje-net/web/pull/296
> Routevents to graphql

- src/activities/resolvers/activity-routes.resolver.ts
- src/activities/services/activity-routes.service.ts
try logging only routes with PR on frontend and see that no activities will be created
> only activity routes endpoint

- src/activities/dtos/update-activity-route.input.ts
- src/activities/resolvers/activity-routes.resolver.ts
- src/activities/services/activity-routes.service.ts
Test with https://github.com/plezanje-net/web/pull/301 FE
> Update activity route mutation

- src/activities/dtos/update-activity.input.ts
- src/activities/resolvers/activities.resolver.ts
- src/activities/services/activities.service.ts
Adds mutation for updating activities, which also takes in possible new routes to add to the activity. Missing lots of validation but basically works.
frontend PR: https://github.com/plezanje-net/web/pull/317
> Update activity mutation

- src/activities/services/activities.service.ts
Test by trying to log something and select date in the future. 
Observ gql error.
> Validate date of acitivity so it cannot be in the future.

- src/crags/dtos/latest-difficulty-votes-service.input.ts
- src/crags/dtos/latest-difficulty-votes.input.ts
- src/crags/resolvers/routes.resolver.ts
- src/crags/services/difficulty-votes.service.ts
- src/crags/utils/paginated-difficulty-votes.ts
Adds query for diff votes ordered by date. Test with https://github.com/plezanje-net/web/pull/392
> add latest diff votes query

- src/activities/entities/activity.entity.ts
- src/activities/services/activity-routes.service.ts
- src/crags/entities/crag.entity.ts
- src/users/entities/club.entity.ts
securing acitivities leaks from crags
> Remove critical field resolvers from entities

- src/ormconfig.ts
Adds back the ormconfig.ts file
> Fix CLI run migrations

- src/users/resolvers/clubs.resolver.ts
- src/users/services/clubs.service.ts
> Fix club slug generation endless loop bug.

- src/crags/services/crags.service.ts
- src/crags/services/routes.service.ts
- src/crags/services/sectors.service.ts
Fixes unpublished contributables being visible to other users and guests
> Publish status params fix

- src/users/resolvers/users.resolver.ts
query was only used with club
it is not needed anymore
test with: https://github.com/plezanje-net/web/pull/449
> Remove user query from user resolver.

- README.md
- package.json
- src/activities/resolvers/activity-routes.resolver.ts
- src/activities/services/activity-routes.service.ts
- src/activities/utils/stats-activities.class.ts
New GraphQL query myActivityStatistics to diplay activity statistics:
{
"myActivityStatistics": [
{
"year": 2023,
"difficulty": 400,
"ascent_type": "onsight",
"nr_routes": 1,
"__typename": "StatsActivities"
},
{
"year": 2020,
"difficulty": 484.09090909090907,
"ascent_type": "redpoint",
"nr_routes": 1,
"__typename": "StatsActivities"
},
...
{
"year": 2023,
"difficulty": 1550,
"ascent_type": "redpoint",
"nr_routes": 2,
"__typename": "StatsActivities"
}
]
}
> New graphQL query myActivityStatistics

- src/activities/services/activity-routes.service.ts
Difficulty of entire MP route was displayed in statistics instead of pitch difficulty.
Fixes #164
> Wrong difficulty for multipitch routes in statistics

- src/crags/entities/crag.entity.ts
- src/migration/1696588233248-activityByMonthNonNullable.ts
- test/e2e/helpers.ts
All crags have the field activityByMonth filled out, so making it non nullable.
> Make activityByMonth field of crag entity non nullable.

- src/app.module.ts
- src/crags/crags.module.ts
- src/crags/entities/crag.entity.ts
- src/crags/entities/parking.entity.ts
- src/crags/entities/sector.entity.ts
- src/crags/resolvers/sectors.resolver.ts
- src/crags/services/parkings.service.ts
- src/migration/1696868866474-addOrientationsEnumArrayField.ts
- src/migration/1696876275575-addApproachTimeField.ts
- src/migration/1696963335256-addWallAnglesEnumArrayField.ts
- src/migration/1697038709137-addSeasonsAndRainProofFields.ts
- src/migration/1697179836611-addCoverImageFieldCrag.ts
- src/migration/1697385889286-addParkingEntity.ts
Adds fields to crag entity:
- orientation
- approachTime
- wallAngles
- seasons
- rainProof
- coverImage
Adds parking entity
Adds parkings field to sector entity.
> Add some fields to crag and sector entity needed on crag info page

- src/activities/services/activity-routes.service.ts
> - fix for my statistics when route difficulty is null [issue169]

- package-lock.json
- package.json
- src/crags/crags.module.ts
- src/crags/entities/area.entity.ts
- src/crags/entities/crag.entity.ts
- src/crags/loaders/area.loader.ts
- src/crags/resolvers/areas.resolver.ts
- src/crags/resolvers/crags.resolver.ts
- src/crags/services/areas.service.ts
- src/crags/services/crags.service.ts
- src/migration/1703958939270-areaSlugNonNullable.ts
- src/migration/1705000587590-fixRainproofFieldName.ts
- src/migration/1705839051844-addNrRoutesByGradeToCrag.ts
- src/migration/1708077643082-addHasSportHasBoulderHasMultipitchToCrag.ts
Fixes missing area slugs.
Adds (temp?) query for all crags (needed by FE crags page).
Renames column rain-proof to rainproof.
Adds a grade distro json field to crag (needed by FE for filtering crags by grade ranges)
> Crags updates

- src/activities/activities.module.ts
- src/app.module.ts
- src/audit/audit.module.ts
- src/crags/crags.module.ts
Adding queue prefix to bull queue
> Add queue prefix

- src/core/utils/contributable-helpers.ts
union query returned entries from other people, but failed to load the contents, so the query resulted in errors
> await isAdmin in contributions union query
