package.json
src/activities/entities/activity-route.entity.ts
src/activities/resolvers/activities.resolver.ts
src/activities/resolvers/activity-routes.resolver.ts
src/activities/services/activities.service.ts
src/activities/services/activity-routes.service.ts
src/activities/utils/route-touched.class.ts
src/migration/1640769431575-convertBoulderFlashToOnsight.ts

based on previous ascents of a route and based on route type.
Way to test this: 
Keep FE on master branch (do it before reject-impossible-logs PR is merged on FE).
Go to a crag and try to log a route with an impossible selection of ascent type.
Limitations are:
- boulders cannot be onsighted. (First try ascent can only be a flash.)
- any route that has already been tried cannot be onsighted or flashed
- any route that has already been ticked cannot be onsighted, flashed or redpointed (can only be repeated)

Add limitations to ascent logs

---

src/crags/services/grading-systems.service.ts

Grades returned should be ordered by difficulty, as FE service expects them to be.
To test check a bouldering area on crags list to see that before the fix the grades were wrongly transformed from difficulty.

Order grades by difficulty

---

src/crags/entities/sector.entity.ts
src/crags/resolvers/sectors.resolver.ts
src/crags/services/sectors.service.ts

Determine if a sector contains only routes of type boulder.
To test this:
use Firecamp to query a crag (e.g. PCL) and request bouldersOnly field on sector

Add bouldersOnly field to sector entity and update resolver.

---

src/activities/activities.module.ts
src/activities/dtos/create-activity-route.input.ts
src/activities/entities/activity-route.entity.ts
src/activities/services/activity-routes.service.ts
src/crags/entities/difficulty-vote.entity.ts
src/migration/1640808395495-userRouteUniqueConstraintOnDiffVote.ts
src/migration/1641581329593-addDefaultIsNotBaseToDifficultyVote.ts

Saves difficulty vote do db or updates it if a user already voted on a route. 
Everything else happens on db level (route difficulty recalculation).
To test this use Firecamp to send createActivity mutation to BE, then observe difficulty_vote and route tables in db.

Add or update difficulty vote if passed alongside activity-route.

---

src/app.module.ts
src/crags/entities/route-event.entity.ts
src/crags/entities/route.entity.ts
src/migration/1642083807909-route-events.ts

Testing: just see that the database migration goes through. The table will be filled with migration script. We will figure out how to do it later with another feature request.
closes #53 
closes #51

add route_events entity and migration

---

src/crags/dtos/create-comment.input.ts
src/crags/dtos/update-comment.ts
src/crags/entities/comment.entity.ts
src/crags/services/comments.service.ts

Add exposedUntil to comments dtos. Check exposedUntil is valid if passed.
Test this by posting exposedUntil field when saving or editing a comment of type warning.
Check date date that is more than 1 month into the future is denied.

Warnings exposedUntil field

---

src/migration/1642534551012-fixMissingRouteDifficulties.ts

Some routes were migrated without difficulty although they were not projects.
Reasons were>
- missing grades
- undetected projects
This PR manually fixes this by running some queries.
Also adds base difficulty votes to votes table.
Run migration, then check some routes that were missing difficulty before
closes #58

Fix routes migrated without difficulty

---

src/core/middleware/check-role.middleware.ts

User object in context has array of role objects (not array of strings).
You can test this by querying a user and trying to get a protected field (eg. user email)
(before this PR it will not work even when you do have an admin role)
nb that directly querying user will not work since user query does not have an auth guard, hence no user object in context.
Try querying for example myClubs, with user subfields...

Fix role middleware

---

src/crags/entities/crag.entity.ts
src/migration/1642708669831-add-crag-type.ts

Creates a new field "type" to the crag entity. It will be used to separate the sport climbing (includes bouldering and sport multipitches) and alpine crags (walls?).
Migration sets all the crags that have peakId filled to alpine.

add crag type property to crags

---

src/crags/entities/grading-system.entity.ts
src/crags/entities/route-type.entity.ts
src/migration/1642796663094-grading-system-route-type.ts

set up grading system <-> route type fields,
make the fields use the correct single join table
update migration to delete the other table
test by running the migration, checking the database and running the following gql:
`{
gradingSystems {
id
name
routeTypes {
name
gradingSystems {
name
}
}
}
}
`

Grading system route type jointable

---

src/activities/dtos/find-activity-routes.input.ts
src/activities/resolvers/activities.resolver.ts
src/activities/services/activity-routes.service.ts

Joined route table in activity routes service find conditions so sorting by grade now works in activity log.
Added resolve field to activity resolver so routes are resolved via service and therefore sorted properly.
To test it open up your climbing log and sort by grade, then open a climbing day, refresh a few times and see that the order of routes does not change.

Activity route sorting

---

src/migration/1642534551012-fixMissingRouteDifficulties.ts

A problem occurs when pulling database from server and then running migration (it was probably a one time thing, but this wont hurt)

ignore database state if difficulties already entered (minor migration fix)

---

src/activities/entities/activity-route.entity.ts
src/activities/services/activity-routes.service.ts
src/crags/entities/pitch.entity.ts
src/migration/1644437266639-makePitchDifficultyANumber.ts

This PR converts pitch difficulty from old string value to new float value that is then used to display grades.
It also adds some logic to sorting activity-routes by grade when a 'route' is actually a single pitch. 
This probably needs more treatment in the future but is a quick fix for properly displaying logs of individual pitches.
Test this with plezanje-net/web#171

Individual pitches logged

---

src/notification/services/notification.service.ts
src/users/dtos/register.input.ts

This PR adds gender to register mutation input. 
It also fixes some gender interpretations on emails as now am O (other) gender type is also possible.
To test no.1 try invoking the register mutation through Firecamp and set gender in input.
To test no.2 go through all processes that send emails using different gender users and check messages.
Can also test with WEB PR plezanje-net/web#194

Registration gender

---

src/crags/entities/pitch.entity.ts

This fixes fails on some crags that contain routes with pitches that have no height.
Since we have many routes with height 0, probably making this field nullable is ok.
Test by opening Paklenica crag.
closes #76

Make pitch height nullable.

---

src/crags/resolvers/search.resolver.ts
src/crags/services/search.service.ts
src/crags/utils/search-results.class.ts

When calling a graphql search query  the service now performs the search only on entities that are requested by the query. 
To test this, execute various search queries through firecamp.

Search optional entities

---

src/crags/crags.module.ts
src/crags/loaders/grading-system.loader.ts
src/crags/loaders/route-type.loader.ts
src/crags/resolvers/crags.resolver.ts
src/crags/resolvers/routes.resolver.ts
src/crags/services/route-types.service.spec.ts
src/crags/services/route-types.service.ts

This should significantly boost crag loading performance.
Try to load kotecnik via firebase before and after.. for me it's 3s -> 700ms on local
query:
```
{
__typename
cragBySlug(slug: "kotecnik") {
id
slug
name
type
orientation
lat
lon
access
description
activityByMonth
peak {
name
slug
__typename
}
area {
id
name
__typename
}
country {
id
name
slug
__typename
}
sectors {
id
name
label
routes {
id
name
slug
difficulty
defaultGradingSystem {
id
__typename
}
isProject
length
routeType {
id
__typename
}
comments {
id
__typename
}
pitches {
difficulty
isProject
number
height
__typename
}
__typename
}
bouldersOnly
__typename
}
comments {
id
content
created
updated
type
exposedUntil
user {
id
fullName
__typename
}
__typename
}
images {
id
title
path
__typename
}
__typename
}
}
```

Dataloading route type and grading system

---

.eslintrc.js
src/activities/entities/activity-route.entity.ts
src/activities/services/activities.service.ts
src/activities/services/activity-routes.service.ts

1.
Logs of type 'repeat' are rejected if a logged route has not been ticked before.
Test by trying to log a route which you haven't ticked and choose repeat for ascentType.
2.
Logging same route multiple times within one log should enforce same restrictions as if each route was logged in its own log. 
Test by trying to log some impossible sequence of same route within one log.
Test through firecamp or through FE if corresponding PR on web has not been merged yet.
Test with plezanje-net/web#202
If testing wit above web PR the easiest way to test this is to make logPossible method of ArtivityFormService always return true (this will in effect disable impossible log checks on FE).

Impossible logs fix

---

src/activities/activities.module.ts
src/activities/dtos/create-activity-route.input.ts
src/activities/services/activity-routes.service.ts
src/app.module.ts
src/crags/entities/route.entity.ts
src/crags/entities/star-rating-vote.entity.ts
src/migration/1647767308908-convertRatingEntityToStarRatingVote.ts
src/migration/1647770003610-addStarRatingToRouteEntity.ts

Backend now handles star rating votes. 
Entity rating was renamed to starRatingVote
A starRating field was added to Route entity
Db trigger was added that recalculates the star rating for a route every time a vote is added.
To test this log some routes with different accounts and observe the db table star_rating_vote and route table (field star_rating).
You can do so via firecamp or with plezanje-net/web#265
Do not forget to run typeorm migrations.
closes #80 
closes #86

Star rating

---

src/migration/1648797413444-fixConvertAscentTypesOnLogDeleteTrigger.ts

Trigger had a bug. 
It used _created_ field from activity route table instead of _date_ field. 
Try to log some ascents 'backwards' by changing the ascent dates and then delete some logs.
Find combination that produces the wrong result. Then apply this fix and check that it works ok now. 
To get the right combos you can refer to the g-docs, namely _possible ascent type sequences_ spreadsheet.

Fix trigger for converting ascent types on log entry deletes.

---

src/crags/services/crags.service.ts

closes #99 
To test, see the crag list, and note that S and Š crags are not mixed together.

Collate when ordering crags

---

src/activities/services/activity-routes.service.ts

There was no backend validaton for this. 
You can test the bug first, either through firecamp or before merging https://github.com/plezanje-net/web/pull/337
Start logging a project, set difficulty vote to some grade, switch to private publish type and see that the diff gets reset and disabled and the form becomes valid (although it shouldn't). Post the form.
After this PR BE should return error and log should fail.

Make difficulty vote mandatory if a project is being ticked.

---

src/activities/activities.module.ts
src/activities/entities/activity-route.entity.ts
src/activities/services/activity-routes.service.ts
src/core/interfaces/order-by-input.interface.ts
src/crags/crags.module.ts
src/crags/dtos/create-route.input.ts
src/crags/dtos/update-route.input.ts
src/crags/entities/route.entity.ts
src/crags/loaders/route-nr-climbers.loader.ts
src/crags/loaders/route-nr-ticks.loader.ts
src/crags/loaders/route-nr-tries.loader.ts
src/crags/resolvers/routes.resolver.ts
src/crags/resolvers/sectors.resolver.ts
src/crags/services/routes.service.ts
src/migration/1652439836973-activity-route-non-nullable.ts

Add field resolvers to get the following counts for a route:
- number of ticks (successful ascents)
- number of tries (all failed + successful ascents)
- number of climbers (distinct people that tried the route)
test through Firecamp and try to fetch these 3 properties on a route and/or test with https://github.com/plezanje-net/web/pull/362

Route ascents count

---

src/crags/dtos/update-route.input.ts
src/crags/services/routes.service.ts

Enable updating base difficulty on routes that have no difficulty votes yet.
to test, try as many different scenarios as possible>
- route with ascents and diff votes (should be denied)
- route with ascents and no diff votes (should be denied)
- route with no ascents and diff votes, if you can find one (should be denied)
- project to graded route
- graded route to project
- change of grade
- invalid data (not project and no diff)
- invalid data (project and diff)
- updating other route data...
and so on...
test with: https://github.com/plezanje-net/web/pull/393

Enable modifying base difficulty of a route.

---

src/app.module.ts
src/auth/auth.module.ts
src/auth/strategies/jwt.strategy.ts
src/users/services/users.service.ts

As we validate user against the database anyway, expiration is not needed in jwt token. This should take care of the problem, where FE considers users as logged in because local storage token expires in 1y while token itself has expiration set to 1 month.
closes https://github.com/plezanje-net/web/issues/367
To test that expiry is really ignored, you can set the expiry to 30s or so and login.. refresh after 30s and see that everything still works.
Will make another PR for frontend, where we log out the user if authentication fails for any reason other than token expiration
also added tolowercase conversion for issue https://github.com/plezanje-net/api/issues/117
closes https://github.com/plezanje-net/api/issues/117

Remove jwt expiration

---

src/activities/resolvers/activities.resolver.ts
src/activities/services/activity-routes.service.ts

closes https://github.com/plezanje-net/web/issues/326
test by opening any activity and see that positions are chronological
see that ascent list stays sorted descending (both use the same service)
wrapped the addition of position sorting that is added to all queries in case position in case position is primary sort field

Sort routes ascending in activity entry view

---

package.json
src/crags/controllers/upload/upload.controller.ts
src/crags/dtos/upload-image.dto.ts
src/crags/entities/image.entity.ts
src/crags/services/images.service.ts
src/migration/1665752351562-updateDbConstraintsOnSomeRelations.ts
src/migration/1665753973994-removePictureAddProfileImageToUser.ts
src/users/entities/user.entity.ts
test/e2e/upload.e2e-spec.ts

Fixes a bug, where image was not saved, but BE already responded and then FE tried to load a nonexistent image file.
User entity had a picture column which was removed. Not clear what was it for (it was all empty).
Image entity had a type column which we do not need anymore. 
The only information to transfer from this column was wether an image is some user's profile image. 
The condition was: type=profile and userId=someuserid
Before deletion a new relation was established between user and image: profileImage
I consider cases (2) where one user had more than one profile image a bug. Was manually chosen which image to keep and the others were discarded.
An author column was added to the image entity, because the uploader is not necessarily also the author.
Some migrations were generated …

Fix upload images async and more

---

package.json
src/activities/entities/activity.entity.ts
src/activities/services/activity-routes.service.ts
src/audit/audit.module.ts
src/auth/guards/roles.guard.ts
src/crags/crags.module.ts
src/crags/dtos/move-route-to-sector.input.ts
src/crags/entities/route.entity.ts
src/crags/resolvers/routes.resolver.ts
src/crags/resolvers/sectors.resolver.ts
src/crags/services/routes.service.ts
src/crags/services/sectors.service.ts
src/crags/utils/convert-ascents.ts
src/crags/utils/generate-slug.ts
src/crags/utils/merge-routes.ts
test/e2e/helpers.ts
test/e2e/routeMigration.e2e-spec.ts
test/e2e/sectorMigration.e2e-spec.ts
test/e2e/sql/triggers.sql
test/jest-e2e.json

- added endpoint for moving sectors to another crag with services that manage related entities
- added endpoint for moving routes between sectors with an option to merge with another route
- moved some ascent validation from activity route service to a helper so it can be used elsewhere
- added triggers to a script to be used by the test database
Route merge is mostly covered by e2e tests, but it would be nice to test this manually with https://github.com/plezanje-net/web/pull/445

Area management tools

---

package.json
src/activities/entities/activity.entity.ts
src/crags/entities/crag-property.entity.ts
src/crags/entities/crag.entity.ts
src/migration/1679818310991-cascadeDeleteCragPropertyFK.ts
src/migration/1679821202524-cascadeNullifyCragActivityFK.ts

When an empty crag is being deleted, also its properties should be automatically deleted, because there is a FK constraint on them. Using cascade delete.
best way to test is: for example with crag Shaddocs -> move all its sectors to another crag, then try deleting it (before running migration). Then run migration and try again...

Add cascade delete to crag property

---

src/auth/services/auth.service.ts
src/users/resolvers/users.resolver.ts
src/users/services/users.service.ts

There was a sequence of actions that might have left the user locked out of her account:
- new user registers
- user loses the registration confirmation link (spam, accidentally deletes mail, forgets to click it...)
- user returns to page and tries to reset the password
- password is successfully reset but user still cannot log in because her active status is false
simple fix: set user active status to true whenever a password is successfully reset.
to test, run above scenario on master to see it fail then on this branch to see it is fixed.

Set user as active whenever a password is successfully reset.

---

src/crags/loaders/route-comments.loader.ts
src/crags/resolvers/crags.resolver.ts
src/crags/services/comments.service.ts

Comments were not being shown for guest users at all (except on home page). 
Comment previews were also not being loaded on route list.
There was a bug introduced with https://github.com/plezanje-net/api/pull/147
(linked to: https://github.com/plezanje-net/web/pull/439)
I am not sure why the condition in comments service:
`    if (!currentUser) {
options.relations = {
crag: true,
};
options.where['crag'] = {
isHidden: false,
};
}`
was even added as comments can only be accessed via crag, via route, via latestComments query, which all already take care of publish status and isHidden status.
(even if we kept this condition it is wrong, as it only takes crag comments into account and fails for route comments --> bug symptom)
Removed some other related unnecessary code.
Might have missed …

Fix bug where comments are not shown if not logged in.

---

src/activities/services/activities.service.ts
src/activities/services/activity-routes.service.ts
src/crags/crags.module.ts
src/crags/resolvers/routes.resolver.ts
src/crags/services/star-rating-votes.service.ts
test/e2e/activity.e2e-spec.ts

Non breaking changes to route field resolvers to support https://github.com/plezanje-net/next-web/pull/40

Route page support

---

src/activities/entities/activity-route.entity.ts
src/activities/services/activity-routes.service.ts
src/crags/entities/crag.entity.ts
src/crags/utils/calculate-scores.ts
src/crags/utils/convert-ascents.ts
test/e2e/activity.e2e-spec.ts
test/e2e/activityMutations.e2e-spec.ts
test/e2e/activityRoutes.e2e-spec.ts
test/e2e/routeMigration.e2e-spec.ts
test/e2e/sectorMigration.e2e-spec.ts
test/e2e/user-delete.e2e-spec.ts

when using nests registerEnumType codegen generates an enum type that can be used in fe as well.
but codegen only considers enum keys of the source, which in generated.ts become values. if we want matching values (db has all lowercase) we need to use lowercase keys when defining an enum in an entity. 
not too nice, since it violates naming convention for enums in typescript, but don't sea a better option to make this work.
test also with https://github.com/plezanje-net/next-web/pull/49

Change case of AscentType enum keys and values to all lowercase.
